### ISSUE TITLE
Blobs module won't start in Production server

### ISSUE THREAD

**Issue by mcolom** [mcolom/ipolDevel#43]
It doesn't start in the production server, but it does in Integration.

Way to reproduce it:

Checkout to prod brach and execute the following in the terminal:

>stopall
core  (http://ipolcore.ipol.im:8080/) is shut down.
demorunner  (http://ipolcore.ipol.im:9004/) is shut down.
proxy  (http://ipolcore.ipol.im:9003/) is shut down.
demoinfo  (http://ipolcore.ipol.im:9002/) is shut down.
archive  (http://ipolcore.ipol.im:9000/) is shut down.
blobs  (http://ipolcore.ipol.im:9001/) is shut down.
>startall
core started, try to ping it.
demorunner started, try to ping it.
proxy started, try to ping it.
demoinfo started, try to ping it.
archive started, try to ping it.
blobs started, try to ping it.

>pingall
core  (http://ipolcore.ipol.im:8080/):  Module active, it says PONG!
demorunner  (http://ipolcore.ipol.im:9004/):  Module active, it says PONG!
proxy  (http://ipolcore.ipol.im:9003/):  Module active, it says PONG!
demoinfo  (http://ipolcore.ipol.im:9002/):  Module active, it says PONG!
archive  (http://ipolcore.ipol.im:9000/):  Module active, it says PONG!
blobs  (http://ipolcore.ipol.im:9001/) : Module unresponsive.

**Comment by mcolom** [comment]
11:38:44 {prod} ~/ipolDevel/ipol_demo/modules/blobs$ ./main.py blobs.conf
Traceback (most recent call last):
  File "./main.py", line 14, in <module>
    from blobs import Blobs
  File "/home/ipol/ipolDevel/ipol_demo/modules/blobs/blobs.py", line 48, in <module>
    auth_file = open('auth', 'r')
IOError: [Errno 2] No such file or directory: 'auth'

**Comment by mcolom** [comment]
I see it's because it's a file which is not archived it git and it's not either in the .gitignore.
It's correct that it's not archived (of course!), but it needs to be in the .gitignore in that case.
I'll do it now, no problem.
